In [68]:
import pandas as pd
import numpy as np
import seaborn as sns
from matplotlib import pyplot as plt

In [69]:
"""import kagglehub
import os
path = kagglehub.dataset_download("irvifa/amazon-product-reviews")
files = os.listdir(path)
file_path = os.path.join(path, 'ratings_Electronics.csv')
df=pd.read_csv(file_path)
df.head()"""

'import kagglehub\nimport os\npath = kagglehub.dataset_download("irvifa/amazon-product-reviews")\nfiles = os.listdir(path)\nfile_path = os.path.join(path, \'ratings_Electronics.csv\')\ndf=pd.read_csv(file_path)\ndf.head()'

In [70]:
df=pd.read_csv('C:/Users/Rishav/Desktop/machine learning/ratings_Electronics.csv')
df.head()

AKM1MP6P0OYPR  0132793040  5.0  1365811200
0  A2CX7LUOHB2NDG  0321732944  5.0  1341100800
1  A2NWSAGRHCP8N5  0439886341  1.0  1367193600
2  A2WNBOD3WNDNKT  0439886341  3.0  1374451200
3  A1GI0U4ZRJA8WN  0439886341  1.0  1334707200
4  A1QGNMC6O1VW39  0511189877  5.0  1397433600

In [71]:
df.columns = ['userId', 'productId', 'ratings','timestamp']
df.head()

userId   productId  ratings   timestamp
0  A2CX7LUOHB2NDG  0321732944      5.0  1341100800
1  A2NWSAGRHCP8N5  0439886341      1.0  1367193600
2  A2WNBOD3WNDNKT  0439886341      3.0  1374451200
3  A1GI0U4ZRJA8WN  0439886341      1.0  1334707200
4  A1QGNMC6O1VW39  0511189877      5.0  1397433600

In [72]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7824481 entries, 0 to 7824480
Data columns (total 4 columns):
 #   Column     Dtype  
---  ------     -----  
 0   userId     object 
 1   productId  object 
 2   ratings    float64
 3   timestamp  int64  
dtypes: float64(1), int64(1), object(2)
memory usage: 238.8+ MB


In [73]:
df.columns

Index(['userId', 'productId', 'ratings', 'timestamp'], dtype='object')

In [74]:
df=df.drop(columns={'timestamp'})
df.head()

userId   productId  ratings
0  A2CX7LUOHB2NDG  0321732944      5.0
1  A2NWSAGRHCP8N5  0439886341      1.0
2  A2WNBOD3WNDNKT  0439886341      3.0
3  A1GI0U4ZRJA8WN  0439886341      1.0
4  A1QGNMC6O1VW39  0511189877      5.0

In [75]:
df[df.isnull().any(axis=1)]

Empty DataFrame
Columns: [userId, productId, ratings]
Index: []

In [76]:
df=df.dropna()
df[df.isnull().any(axis=1)],df.head()

(Empty DataFrame
 Columns: [userId, productId, ratings]
 Index: [],
            userId   productId  ratings
 0  A2CX7LUOHB2NDG  0321732944      5.0
 1  A2NWSAGRHCP8N5  0439886341      1.0
 2  A2WNBOD3WNDNKT  0439886341      3.0
 3  A1GI0U4ZRJA8WN  0439886341      1.0
 4  A1QGNMC6O1VW39  0511189877      5.0)

In [77]:
df.head()

userId   productId  ratings
0  A2CX7LUOHB2NDG  0321732944      5.0
1  A2NWSAGRHCP8N5  0439886341      1.0
2  A2WNBOD3WNDNKT  0439886341      3.0
3  A1GI0U4ZRJA8WN  0439886341      1.0
4  A1QGNMC6O1VW39  0511189877      5.0

In [78]:
dd = df.sort_values(by='productId')
dd.reset_index(drop=True, inplace=True)
dd.head()

userId   productId  ratings
0  A2CX7LUOHB2NDG  0321732944      5.0
1  A2NWSAGRHCP8N5  0439886341      1.0
2  A2WNBOD3WNDNKT  0439886341      3.0
3  A1GI0U4ZRJA8WN  0439886341      1.0
4  A1QGNMC6O1VW39  0511189877      5.0

In [79]:
dd['Count'] = dd.groupby('productId')['productId'].transform('count')
dd.head()

userId   productId  ratings  Count
0  A2CX7LUOHB2NDG  0321732944      5.0      1
1  A2NWSAGRHCP8N5  0439886341      1.0      3
2  A2WNBOD3WNDNKT  0439886341      3.0      3
3  A1GI0U4ZRJA8WN  0439886341      1.0      3
4  A1QGNMC6O1VW39  0511189877      5.0      6

In [80]:
dd.shape

(7824481, 4)

In [81]:
popularity_threshold = 1000
dd= dd.query('Count >= @popularity_threshold')
dd.head()

userId   productId  ratings  Count
182   AZFF4CX9MQ4AE  0972683275      5.0   1051
183  A39LNFWIZZT0VW  0972683275      5.0   1051
184  A16Y72DRF7ITNB  0972683275      3.0   1051
185   AU1I7HEEZJCSY  0972683275      5.0   1051
186   A6TWN9W9WSAV0  0972683275      4.0   1051

In [82]:
dd.shape

(1379717, 4)

In [83]:
dd['productId'].value_counts().sort_values(ascending=False)

productId
B0074BW614    18244
B00DR0PDNE    16454
B007WTAJTO    14172
B0019EHU8G    12285
B006GWO5WK    12226
              ...  
B004XZHY34     1003
B000067O5G     1003
B000IF4788     1001
B0007LJHVA     1000
B00077AA5Q     1000
Name: count, Length: 667, dtype: int64

In [84]:
dd.columns
dd = dd.drop('Count',axis=1)

In [85]:
dd = pd.pivot_table(dd.head(200000), index='userId', columns='productId', values='ratings', aggfunc='mean')
dd.columns = [f'product{col}' for col in dd.columns]
dd = dd.reset_index()
dd.head()

userId  product0972683275  productB00001P4ZH  \
0  A000428226SAAAIBK8I36                NaN                NaN   
1   A000681618A3WRMCK53V                NaN                NaN   
2  A00177463W0XWB16A9O05                NaN                NaN   
3   A0023922YYT81KP1CWU4                NaN                NaN   
4  A00328401T70RFN4P1IT6                NaN                NaN   

   productB00001WRSJ  productB00004SABB  productB00004SB92  productB00004T8R2  \
0                NaN                NaN                NaN                NaN   
1                NaN                NaN                NaN                NaN   
2                NaN                NaN                NaN                NaN   
3                NaN                NaN                NaN                NaN   
4                NaN                NaN                NaN                NaN   

   productB00004ZCJE  productB00005ATMB  productB00005LEN4  ...  \
0                NaN                NaN                NaN  ...   
1                NaN                NaN                NaN  ...   
2                NaN                NaN                NaN  ...   
3                NaN                NaN                NaN  ...   
4                NaN                NaN                NaN  ...   

   productB000S5Q9CA  productB000SMVQK8  productB000TXZIDM  productB000U5TUWE  \
0                NaN                NaN                NaN                NaN   
1                NaN                NaN                NaN                NaN   
2                NaN                NaN                NaN                NaN   
3                NaN                NaN                NaN                NaN   
4                NaN                NaN                NaN                NaN   

   productB000UEZ36W  productB000UHQVOW  productB000V1MLBE  productB000V7AF8E  \
0                NaN                NaN                NaN                NaN   
1                NaN                NaN                NaN                NaN   
2                NaN                NaN                NaN                NaN   
3                NaN                NaN                NaN                NaN   
4                NaN                NaN                NaN                NaN   

   productB000VM60I8  productB000VX6XL6  
0                NaN                NaN  
1                NaN                NaN  
2                NaN                NaN  
3                NaN                NaN  
4                NaN                NaN  

[5 rows x 110 columns]

In [86]:
dd=dd.fillna(0)
dd.head(),dd.shape

(                  userId  product0972683275  productB00001P4ZH  \
 0  A000428226SAAAIBK8I36                0.0                0.0   
 1   A000681618A3WRMCK53V                0.0                0.0   
 2  A00177463W0XWB16A9O05                0.0                0.0   
 3   A0023922YYT81KP1CWU4                0.0                0.0   
 4  A00328401T70RFN4P1IT6                0.0                0.0   
 
    productB00001WRSJ  productB00004SABB  productB00004SB92  productB00004T8R2  \
 0                0.0                0.0                0.0                0.0   
 1                0.0                0.0                0.0                0.0   
 2                0.0                0.0                0.0                0.0   
 3                0.0                0.0                0.0                0.0   
 4                0.0                0.0                0.0                0.0   
 
    productB00004ZCJE  productB00005ATMB  productB00005LEN4  ...  \
 0                0.0             

In [87]:

def matrix_factorization(R, P, Q, K, steps=5000, alpha=0.0001, beta=0.002,decay_rate=0.95):

    Q = Q.T
    for step in range(steps):
        for i in range(len(R)):
            for j in range(len(R[i])):
                if R[i][j] > 0 and R[i][j]<=5:
                    eij = R[i][j] - np.dot(P[i, :], Q[:, j])
                    for k in range(K):
                         P[i][k] = np.clip(P[i][k] + alpha * (2 * eij * Q[k][j] - beta * P[i][k]), -1e5, 1e5)
                         Q[k][j] = np.clip(Q[k][j] + alpha * (2 * eij * P[i][k] - beta * Q[k][j]), -1e5, 1e5)


        loss = 0
        for i in range(len(R)):
            for j in range(len(R[i])):
                if R[i][j] > 0 and R[i][j]<=5:
                    loss += (R[i][j] - np.dot(P[i, :], Q[:, j])) ** 2
                    loss += beta * (np.sum(P[i, :] ** 2) + np.sum(Q[:, j] ** 2))

      ##  alpha *= decay_rate
        ##beta *= decay_rate

        if loss < 0.001:
            break

    return P, Q.T

In [88]:
matrix = dd.values[:1000, 1:100]
##rank = np.linalg.matrix_rank(matrix.to_numpy(dtype='float64'))
##rank

In [89]:
R = matrix
N = R.shape[0]
M = R.shape[1]
K =4;##rank


P = np.random.rand(N, K)*0.1
Q = np.random.rand(M, K)*0.1

U, V = matrix_factorization(R, P, Q, K)
print("U",U)
print("v",V)


U [[0.95316181 0.54107724 0.60331978 0.59322815]
 [0.22218324 0.38742204 0.31759052 0.19009886]
 [0.55705687 0.29639246 0.39594373 0.36978447]
 ...
 [1.06512844 0.66458089 0.87128266 0.65421948]
 [0.30231656 0.28213928 0.2041376  0.26702269]
 [0.45137593 0.75208393 0.78520822 0.58248899]]
v [[1.63781802 1.3602349  1.77299173 1.93642305]
 [2.01320663 1.99711464 2.14565838 2.37025766]
 [1.75491944 2.00566197 2.19902341 1.67015181]
 [1.58717732 1.72452936 0.9587386  1.84082422]
 [1.95088753 1.79424192 1.33483339 1.16642324]
 [1.71479257 1.87097389 1.75852025 1.58247196]
 [1.51358807 2.01659033 1.48307185 0.55845988]
 [1.74161965 1.86823075 1.57097724 1.15804832]
 [0.98571689 1.51135495 1.46325443 1.28831546]
 [1.38777975 1.40339654 0.91861154 1.56610703]
 [1.55173726 2.3644316  1.30606497 2.08055603]
 [1.51058496 1.39478039 1.51981857 1.62728387]
 [1.59135908 1.45637019 1.45187087 1.74090787]
 [1.16952586 0.83467123 1.63334794 1.77979571]
 [1.36682083 0.98332414 2.03559203 1.94978493]
 [2

In [90]:
R_approx = np.dot(U, V.T)

print("Original matrix (R):")
print(R[:, :])
print("\nApproximated matrix (R_approx):")
print(R_approx[:, :])

Original matrix (R):
[[0.0 0.0 0.0 ... 0.0 0.0 0.0]
 [0.0 0.0 0.0 ... 0.0 0.0 0.0]
 [0.0 0.0 0.0 ... 0.0 0.0 0.0]
 ...
 [0.0 0.0 0.0 ... 0.0 0.0 0.0]
 [0.0 0.0 0.0 ... 0.0 0.0 0.0]
 [0.0 0.0 0.0 ... 0.0 0.0 0.0]]

Approximated matrix (R_approx):
[[4.51551938 5.70012666 5.07543562 ... 5.52154101 5.4835411  5.16091808]
 [1.82207788 2.35305105 2.1828343  ... 2.30875782 2.21911997 2.01319163]
 [2.73358529 3.43944477 3.06033875 ... 3.29829015 3.31507357 3.07499321]
 ...
 [5.46009531 6.89171155 6.21075605 ... 6.62968017 6.66987292 6.13557865]
 [1.75791838 2.24301233 1.99128903 ... 2.18919674 2.09739855 1.98366294]
 [4.28239522 5.47614841 5.00009082 ... 5.22701023 5.13648508 4.52469369]]


In [91]:
from sklearn.metrics.pairwise import cosine_similarity
R.shape,R_approx.shape,R_approx[R_approx>5]

((1000, 99),
 (1000, 99),
 array([5.70012666, 5.07543562, 5.81299337, ..., 5.80067384, 5.22701023,
        5.13648508]))

In [92]:
similarity = cosine_similarity(R, R_approx)
print("Cosine Similarity:\n", similarity)

Cosine Similarity:
 [[0.10749129 0.09955845 0.10727955 ... 0.10655148 0.1035317  0.09891   ]
 [0.09562898 0.10452443 0.09545937 ... 0.09767004 0.09653692 0.1019764 ]
 [0.10749129 0.09955845 0.10727955 ... 0.10655148 0.1035317  0.09891   ]
 ...
 [0.08885683 0.08475724 0.08882671 ... 0.08889008 0.08554584 0.08388818]
 [0.10869678 0.1048218  0.10801027 ... 0.10683169 0.1094713  0.10447231]
 [0.10211907 0.11224982 0.10294173 ... 0.10482836 0.10427443 0.1128874 ]]


In [93]:
for i in np.arange(0, 1.1, 0.1):
   mask = R != 0
   accuracy = np.mean((abs(R - R_approx)<=i)[mask] )
   print(f"Accuracy for difference {i*1:.1f} is : {accuracy * 100:.2f}%")

Accuracy for difference 0.0 is : 0.00%
Accuracy for difference 0.1 is : 93.49%
Accuracy for difference 0.2 is : 95.38%
Accuracy for difference 0.3 is : 96.85%
Accuracy for difference 0.4 is : 98.00%
Accuracy for difference 0.5 is : 98.84%
Accuracy for difference 0.6 is : 99.16%
Accuracy for difference 0.7 is : 99.26%
Accuracy for difference 0.8 is : 99.37%
Accuracy for difference 0.9 is : 99.58%
Accuracy for difference 1.0 is : 99.89%


In [94]:
import math
testData=20000;
testDataRow=math.floor(testData*0.8);
testDataColumn=math.floor(dd.shape[1]*0.8);
matrix = dd.head(testData).values[:, 1:]
R = matrix[:,:testDataColumn]
N = R.shape[0]
M = R.shape[1]
K =4;##rank


P = np.random.rand(N, K)*0.1
Q = np.random.rand(M, K)*0.1

User_feature, vv = matrix_factorization(R, P, Q, K)
R = matrix[0:testDataRow,:]
N = R.shape[0]
M = R.shape[1]
K =4;##rank


P = np.random.rand(N, K)*0.1
Q = np.random.rand(M, K)*0.1

uu, movie_feature = matrix_factorization(R, P, Q, K)
print("user_feature",User_feature)
print("movie_feature",movie_feature)

user_feature [[0.41158454 0.36736946 0.40240045 0.37394255]
 [0.15289104 0.11339283 0.14180057 0.14451868]
 [0.26184274 0.18238919 0.27266572 0.21550246]
 ...
 [0.02603143 0.05701456 0.0486474  0.04759118]
 [0.32918438 0.27048612 0.27589835 0.27946608]
 [0.09449576 0.02738022 0.09188913 0.02031796]]
movie_feature [[2.45485526 3.06191626 2.7988588  4.24750163]
 [2.14391716 3.70411641 4.31111761 3.32621186]
 [3.4732944  3.18837149 4.21430874 3.79134962]
 [1.8907215  2.11438879 2.46208728 4.72007899]
 [3.46311505 3.18255642 3.27957262 3.31672838]
 [2.32620004 5.19406515 2.39295177 2.97684421]
 [4.82773018 3.71491247 1.85730775 3.31615141]
 [3.27625703 2.80967432 3.11976762 4.13586063]
 [3.95768571 3.59670678 3.47542512 3.32847221]
 [3.97510074 3.76601909 3.25802368 1.22437451]
 [3.52150126 4.08331648 2.46108626 3.7786046 ]
 [2.76445292 3.11351083 3.23770117 3.47565132]
 [2.84759401 3.62773363 4.55433784 1.96457099]
 [3.71386127 3.05646209 3.1743655  3.48474782]
 [2.77781994 3.26962592 2.4

In [95]:
User_feature.shape,movie_feature.shape

((20000, 4), (109, 4))

In [96]:
matrix_test=matrix[testDataRow:testData,testDataColumn:]
matrix_test[matrix_test != 0],matrix_test.shape

(array([3.0, 4.0, 5.0, 5.0, 5.0, 5.0, 5.0, 4.0, 4.0, 4.0, 5.0, 4.0, 5.0,
        5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 4.0, 5.0,
        5.0, 2.0, 5.0, 5.0, 5.0, 3.0, 5.0, 1.0, 5.0, 5.0, 5.0, 4.0, 5.0,
        4.0, 5.0, 5.0, 5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 4.0, 5.0, 5.0, 1.0,
        3.0, 5.0, 1.0, 5.0, 5.0, 5.0, 1.0, 5.0, 5.0, 5.0, 1.0, 5.0, 5.0,
        5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 1.0, 5.0, 5.0, 2.0, 5.0, 5.0, 4.0,
        5.0, 5.0, 5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 4.0, 3.0, 5.0, 4.0, 3.0,
        3.0, 5.0, 5.0, 5.0, 2.0, 1.0, 5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 5.0,
        5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 5.0, 1.0, 5.0, 5.0, 3.0,
        4.0, 5.0, 1.0, 1.0, 5.0, 3.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 4.0,
        5.0, 4.0, 1.0, 5.0, 5.0, 5.0, 5.0, 5.0, 2.0, 5.0, 5.0, 5.0, 5.0,
        4.0, 5.0, 5.0, 1.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0,
        5.0, 5.0, 1.0, 5.0, 5.0, 5.0, 4.0, 1.0, 1.0, 1.0, 5.0, 5.0, 1.0,
        5.0, 3.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0

In [97]:
testDataRow,testDataColumn,matrix.shape
matrix[:testDataRow,:testDataColumn][matrix[:testDataRow,:testDataColumn] != 0],np.dot(User_feature,movie_feature.T)[:testDataRow,:testDataColumn][matrix[:testDataRow,:testDataColumn] != 0]

(array([5.0, 2.0, 3.0, ..., 5.0, 5.0, 5.0], dtype=object),
 array([4.85633312, 1.86593992, 2.91564864, ..., 4.69142629, 4.66305922,
        4.610055  ]))

In [98]:
matrix_predict=(np.dot(User_feature,movie_feature.T))[testDataRow:testData,testDataColumn:]
matrix_predict[matrix_test != 0],matrix_predict.shape

(array([0.53462912, 0.63469466, 0.65054427, 0.5483736 , 0.76984305,
        0.59550002, 0.46234631, 0.75536436, 0.79063475, 0.34829922,
        0.94525391, 0.37031708, 0.98491925, 0.64731434, 1.01739185,
        0.47668026, 0.67926242, 5.1517634 , 0.72256034, 0.94045876,
        0.58864616, 0.67132715, 3.91502177, 0.59546368, 0.86154914,
        0.9048666 , 0.88784683, 0.45366984, 0.94259621, 0.61458321,
        4.55404478, 0.99372071, 0.82172971, 0.76192445, 0.73936422,
        0.78373881, 0.95931954, 0.83564055, 0.57667929, 0.35002288,
        0.87504336, 1.0451332 , 4.81373274, 0.67197767, 0.43765624,
        0.2909849 , 0.73718383, 0.84629351, 0.75178825, 0.89273893,
        0.66474955, 0.64599634, 0.65723047, 0.88968853, 4.88262417,
        0.81606178, 0.75992212, 0.43491071, 0.67027846, 0.53118167,
        5.03213308, 4.19665161, 0.58180893, 0.59981477, 0.43467847,
        0.48820765, 0.45388003, 5.12319638, 0.44881961, 0.76739428,
        0.41984714, 4.19411953, 0.9190256 , 0.31

In [101]:
for i in np.arange(0, 1.1, 0.1):
   mask = matrix_test != 0
   accuracy = np.mean((abs(matrix_test - matrix_predict)<=i)[mask] )
   print(f"Accuracy for difference {i*1:.1f} is : {accuracy * 100:.2f}%")

Accuracy for difference 0.1 is : 0.00%
Accuracy for difference 0.2 is : 8.00%
Accuracy for difference 0.3 is : 15.00%
Accuracy for difference 0.4 is : 32.00%
Accuracy for difference 0.5 is : 47.00%
Accuracy for difference 0.6 is : 49.00%
Accuracy for difference 0.7 is : 56.00%
Accuracy for difference 0.8 is : 60.00%
Accuracy for difference 0.9 is : 61.00%
Accuracy for difference 1.0 is : 69.00%


In [102]:
mask = matrix_test != 0
rmse = np.sqrt(np.mean((matrix_test[mask] - matrix_predict[mask])**2))
print(f"RMSC is : {rmse}")

RMSC is  1.252718635247
